language: scala

scala:
  - "2.11.8"
  - "2.12.2"

sudo: false

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - oraclejdk8

# Cache bootstrap and dependency files for (hopefully) faster builds, per recommendation in
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
